// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywkingoohiahocvibhsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3a2luZ29vaGlhaG9jdmliaHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTQxODMsImV4cCI6MjA3MDMzMDE4M30.6KY5LjXshR8A7d4W6ag7sCu52Cc3h9q1j9fzYusWif8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});